# ファイル名をhydra.yamlに変更するとエラーが発生するため注意

# exp/exp1.yamlファイルを読み込み
# ファイル名が自動で実験名になる
defaults: &exp
  - exp: example

# default から自動取得
exp_id:
  <<: *exp

hydra:
  run:
    dir: ../logs/hydra/${exp_id.exp}/${now:%y%m%d_%H%M%S}
  job_logging:
    formatters:
      file:
        format: "[%(levelname)s] %(asctime)s - %(name)s \n %(message)s"
      console:
        format: "%(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: console
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        level: NOTSET
        formatter: file
    root:
      level: NOTSET
      handlers:
        - console
        - file

